services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: piklnk
      POSTGRES_PASSWORD: piklnk
      POSTGRES_DB: piklnk_db
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U piklnk -d piklnk_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
